version: '3.3'
services:
  db:
    image: mysql:8.0.23
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      JWT_SECRET: secret
    restart: 'always'
    